### PR TITLE
Update priority-roll.md

### PR DESCRIPTION
**Pull request by mabenoi**
Translated in french

### CODE REVIEW

**Comment by arturmuller** [comment]
Hey @mabenoi! Thanks a lot, this is great. I don't speak French, so can't check it for accuracy, but from a technical perspective, everything is perfectly in order. ✨ 

I merged it in manually because this PR was opened from the `table` branch, and it was confusing GitHub a bit. If possible, it is generally preferrable to branch out from the `master` branch. (It doesn't matter too much, but it makes it a bit nicer to see who is actually responsible for each commit...)

**Comment by mabenoi** [comment]
Great! I'll be sure to do that next time. Rest assure the translation is
good. I'm pretty hyped to contribute to this project. I'll Translate more
later this week.
Have a good day!

Le dim. 3 nov. 2019 à 10:06, Artur Muller <notifications@github.com> a
écrit :

**Comment by arturmuller** [comment]
That's great to hear! Looking forward to it! :)

**Comment by arturmuller** [comment]
BTW, @mabenoi, let me know what you want to link to from you name in the [Credits](https://github.com/arturmuller/battle-tracker-content#credits) (in the future, this will also be used in the app to credit the translators for each language.)

**Pull request closed without merging**
