### PR TITLE
Update thanks.md

### PR DESCRIPTION
**Pull request by Farmercoho**
First time using git. Tell me if anything is wrong :l

### CODE REVIEW

**Comment by arturmuller** [comment]
Hi @Farmercoho — all good. 👌

Thanks for the first contribution! :)

**Comment by arturmuller** [comment]
BTW, @Farmercoho, let me know what you want to link to from you name in the [Credits](https://github.com/arturmuller/battle-tracker-content#credits) (in the future, this will also be used in the app to credit the translators for each language.)

**Comment by Farmercoho** [comment]
Cool, just call me "HooTie" on there.

**Comment by arturmuller** [comment]
Righto. And do you want a link to some website/social media profile or just the name?

**Comment by Farmercoho** [comment]
Just the name is fine :)

**Pull request merged**
